### ISSUE TITLE
UNNotificationServiceExtension not working

### ISSUE THREAD

**Issue by appcelerate** [OneSignal/OneSignal-iOS-SDK#104]
`- (void)didReceiveNotificationRequest:(UNNotificationRequest *)request withContentHandler:(void (^)(UNNotificationContent * _Nonnull))contentHandler {`

not called.

only the method 

`- (void) application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo
//fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler`

will called. I can't find any helpful links in the doc.

Any ideas :/ ?

**Comment by JKalash** [comment]
Are you sending content-available - 1 or ios_attachments through our push notification? If so, they will not trigger your extension. You should make sure to pass mutable-content = 1 and pass your data as part of the additionalData section and not ios_attachments in order to trigger your service extension.
