### ISSUE TITLE
Short link added in push notification

### ISSUE THREAD

**Issue by vmosconecds** [OneSignal/OneSignal-iOS-SDK#1054]
**Description:**

When adding a short link (example: https://tinyurl.com/aTinyUrl) into the launch URL I'm getting a blank dialog.

![File](https://user-images.githubusercontent.com/14130611/155407285-cecc3c5b-9cfe-45a9-a5d5-d7d2cf735f82.jpg)

**Environment:**

iOS: 15
Using Cocoapods

Setting `OneSignal.setLaunchURLsInApp(true)`

**Steps to Reproduce Issue:**

1 - Send push notification with a short link (https://tinyurl.com/aTinyUrl)
2 - Click push notification

**Comment by emawby** [comment]
@vmosconecds Thank you for reaching out. When I try to access that link I am getting an error in my browser. Are there any other functional URLs that you are having this issue with?

**Comment by vmosconecds** [comment]
@emawby yes, you can create your own link here [link](https://tinyurl.com/)

**Comment by robseekr** [comment]
https://tinyurl.com/2tn39tba

**Comment by vmosconecds** [comment]
@emawby Is there a way in which the link can be handle by the app itself? (Not displaying a dialog)

**Comment by emawby** [comment]
@vmosconecds Yes instead of using the launchURL field you can put the url with an appropriate key in the additional data field. Then use the [notificationOpened handler ](https://documentation.onesignal.com/docs/sdk-notification-event-handlers#notification-opened-event) and parse the url from the result.notification.additionalData dictionary

**Comment by emawby** [comment]
@vmosconecds Hello! Does the method above work for you and is there any other outstanding issue or can this be closed?
