### ISSUE TITLE
iOS 9 shows UIAlertView with disabled configuration

### ISSUE THREAD

**Issue by arturmichna** [OneSignal/OneSignal-iOS-SDK#106]
SDK: 2.1.16
iOS: 9.3.3

Using settings with inAppAlerts disabled shows UIAlertView/Controller when received notification instead of calling handleNotificationAction:
@{kOSSettingsKeyInFocusDisplayOption: @(OSNotificationDisplayTypeNotification),
                                  kOSSettingsKeyInAppAlerts : @NO, kOSSettingsKeyAutoPrompt: @NO};

**Comment by jkasten2** [comment]
@arturmichna This behavior is intentional, if you disable the display behavior only the [handleNotificationReceived](https://documentation.onesignal.com/docs/ios-native-sdk#section--handlenotificationreceived-) block will fire.

Also note that `kOSSettingsKeyInAppAlerts` is deprecated and will be removed in a future major release. Please use [kOSSettingsKeyInFocusDisplayOption](https://documentation.onesignal.com/docs/ios-native-sdk#section--kossettingskeyinfocusdisplayoption-) instead.

Thanks.

**Comment by arturmichna** [comment]
Setting OSNotificationDisplayTypeNotification displays UIAlertViewController in iOS9. Setting OSNotificationDisplayTypeNone will not call handleNotificationAction block. I could not use 
I would like to handle notification when app is in focus (both in iOS 9 and 10) but without showing Alert or InAppNotification. Is there an ability to do this? I cannot use UNUserNotificationCenterDelegate as I need to support iOS 9 also.

**Comment by jkasten2** [comment]
@arturmichna I recommend setting `OSNotificationDisplayTypeNone`. This will trigger still trigger [handleNotificationReceived](https://documentation.onesignal.com/docs/ios-native-sdk#section--handlenotificationreceived-) when the notification is received while the app is in the forground on all verions of iOS.

You will still need the [`handleNotificationAction`](https://documentation.onesignal.com/docs/ios-native-sdk#section--handlenotificationaction-) block setup so you can handle notification clicks from the notification center however.

**Comment by arturmichna** [comment]
Thanks! Marking as resolved
