### ISSUE TITLE
[question]: Action Buttons and Rich Notification question.

### ISSUE THREAD

**Issue by nick-softwaredev** [OneSignal/OneSignal-iOS-SDK#1199]
### How can we help?

Good Day everyone, 

I have fairly rookie question. 

In documentation, there is a description how to setup action buttons. My one signal sdk in  is setup and running. When I setup action buttons in push settings in dashboard and assign category I do not see buttons inside notification I receive on my test device unless I manually register exact categorie and buttons in app code notification center itself. Is this expected behavior? What I need is being able to setup new buttons on dashboard and  handle them in notification without doing additional work in code. But maybe this is not supposed to work like this. 

Thanks in advance  for a reply! 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@nick-softwaredev if you want to use the "Action Buttons" under the "Advanced Settings" when sending a notification you must NOT set "Category" under the platform setting for iOS on the notification. This is because the OneSignal SDK needs to create a dynamic one when the notification is received to create a temporary category.

**Comment by nick-softwaredev** [comment]
@jkasten2 thank you! You saved me big time.
 
I could not find any information about this in the official documentation, some updates needed in there for sure.
