### ISSUE TITLE
[Bug]: Asset validation failed (50) The app references non-public selectors in Payload/Runner.app/Frameworks/OneSignalFramework.framework/OneSignalFramework: setSharedInstance

### ISSUE THREAD

**Issue by Eddayy** [OneSignal/OneSignal-iOS-SDK#1370]
### What happened?

When I upload my app to apple connect, apple will reject the ipa and says the app has non public selectors. I'm also using flutter and fastlane to upload to app store, i've also post this in the flutter repo but i think here is relevant since it's a bug on the native code?

### Steps to reproduce?

```Markdown
1. Install `onesignal_flutter: ^5.1.0`
2. Follow setup guide
3. Build IPA
4. Upload to Apple connect
```

### What did you expect to happen?

For the ipa to uploade successfully

### OneSignal iOS SDK version

5.1.0

### iOS version

15

### Relevant log output

```Shell
[!] Error uploading ipa file: 
 [Application Loader Error Output]: ERROR: [ContentDelivery.Uploader] Asset validation failed (50) The app references non-public selectors in Payload/Runner.app/Frameworks/OneSignalFramework.framework/OneSignalFramework: setSharedInstance: (ID: 4b3297b1-4a68-4ade-aa94-b1cc19f3b90d)
[Application Loader Error Output]: Error uploading '/var/folders/bf/fz1p4pms3k5bjl9x1sqvzf880000gp/T/ed36fbfb-4a1e-481c-86ae-dfa20e10ed76.ipa'.
[Application Loader Error Output]: Asset validation failed The app references non-public selectors in Payload/Runner.app/Frameworks/OneSignalFramework.framework/OneSignalFramework: setSharedInstance: (ID: 4b3297b1-4a68-4ade-aa94-b1cc19f3b90d) (50)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @Eddayy, Is this the first time you are uploading with the OneSignal SDK?

I am confused by this because the only call the SDK makes to a method called `setSharedInstance` is the SDK's own method, and not a non-public selector. [Here](https://github.com/OneSignal/OneSignal-iOS-SDK/blob/8f47b6fca513ac848634c31052080ae2f3d9e915/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L792).

Can you try again?

I looked up this error. Make sure that you are distributing your app using the release scheme instead of the debug scheme, or try again as some people reported flakiness with the validation.

**Comment by Eddayy** [comment]
Thanks for the speedy response!

Yes, this is the first time I've uploaded with OneSignal SDK, I've tried again and apple still rejects my uploads, I also confirmed that I'm using release scheme. Is there any info I can provide to help?

**Comment by Eddayy** [comment]
Oh if I downgrade to 3.12.7, I can upload to apple.

**Comment by Eddayy** [comment]
looking around, seems like the solution is just to rename the method https://github.com/GetStream/stream-chat-swift/issues/1177
