### ISSUE TITLE
[question]: Apns Bad Device Token	

### ISSUE THREAD

**Issue by weiqingtangx** [OneSignal/OneSignal-iOS-SDK#1394]
Hi there,

Currently, I was integrating OneSignal into my iOS App. The integration code is pretty easy, but it sounds like I always receive the "Apns Bad Device Token" in the below image. I installed my app from TestFlight, the first time the push was working, and then I deleted my app and reinstalled it again. I see the errors "Apns Bad Device Token" on the blew image. 

```
 pod 'OneSignal/OneSignal', '5.1.3'

- (void)registOneSignalNotifcation:(NSDictionary *)launchOptions {
      [OneSignal.Debug setLogLevel:ONE_S_LL_VERBOSE];
      [OneSignal initialize:ONESIGANL_APPID withLaunchOptions:launchOptions];
      [OneSignal.Notifications requestPermission:^(BOOL accepted) {
        NSLog(@"User accepted notifications: %d", accepted);
      } fallbackToSettings:true];
    
    [OneSignal.Notifications addClickListener:self];
}

 //after login 
 [OneSignal login:userName];

//the error from curl request
{"id":"77cacd79-4952-40d2-b756-a265ca886d2d","external_id":null,"errors":{"invalid_aliases":{"external_id":["xxxx"]}}}%   
```
I guess the problem is  I logined twice?

![image](https://github.com/OneSignal/OneSignal-iOS-SDK/assets/5905640/cf75faa8-e546-4327-82c8-fb15c96eb77a)

**Comment by jkasten2** [comment]
@weiqingtangx This "Apns Bad Device Token" status happens when you send a notification but OneSignal gets a rejection from Apple the token isn't valid. There are a few reason this can happen and it is covered in this guide:
https://documentation.onesignal.com/docs/mismatched-user-environment

Let us know if that fixes it for you, or if you continue to see this issue.

**Comment by weiqingtangx** [comment]
@jkasten2 Thank you for your quick response, I will investigate my issue with your link.

**Comment by weiqingtangx** [comment]
@jkasten2 I think the issue might be I misuploaded the sanbox p12 ceterficate, I switched to the nonsanbox certificate, it looks good now. Thank you!

Another quick question, I noticed when I installed my App, I always got a message(You have recalled a message) automatically at first time which I did not push, do you have any idea about this?

![image](https://github.com/OneSignal/OneSignal-iOS-SDK/assets/5905640/a7250531-88a7-40a2-b0bb-8f086124f264)

**Comment by jkasten2** [comment]
@weiqingtangx I have never seen a "You have recalled a message" notification like this before,, OneSignal doesn't send or display any notifications by default. Is it possible someone on your team sent it? Or do you have any other libraries / SDKs in your app that could be displaying this notification?

**Comment by weiqingtangx** [comment]
@jkasten2 Yes, I do have the second Push SDK, we are working on the migration to the OneSignal SDK. I will investigate on our side. Thank you again, I will close it. Have a good day.

**Comment by pierroo** [comment]
I don't meant to reopen it, but I also started getting this "apns bad device token" since I upgdated from v4 to v5 of Onesignal.
I haven't changed anything on my end (except using the new methods)

Your link https://documentation.onesignal.com/docs/mismatched-user-environment
doesn't seem to exist anymore, can you forward me where the information is now?
Thank you @jkasten2
