### ISSUE TITLE
Please notify users when major SDK changes take place (Firebase)

### ISSUE THREAD

**Issue by mitchellkrogza** [OneSignal/OneSignal-iOS-SDK#167]
It was only by chance that this morning I stumbled across an **updated** article of yours on how to configure Android push notifications which I had previously enabled already 6 months ago on all my apps. 

I only noticed this because when I clicked on stats for one of my apps the amount of Android subscribers was a horrible ZERO .... I then went into the app settings on all my OneSignal apps and my previous Google API and Project ID's entered when I originally setup all my sites were all missing the project Id field.

I went through getting a new server API key and Project ID's from Firebase and hope that fixes it now but please in future is there possibly any chance you can communicate with your userbase to notify them that a major change has taken effect and certain app functions will cease functioning altogether unless changes are made.

What troubles me is that all my apps had android subscribers (one had several hundred) and now they are all zero, that peaves me quite a bit.

https://documentation.onesignal.com/docs/generate-a-google-server-api-key

**Comment by jkasten2** [comment]
@mitchellkrogza Sorry to hear about your subscriber issue, we have ensured that none of our recent changes should effect existing subscribers or projects. This includes continuing to use GCM projects instead of FCM. Also if you are using an older SDK and/or haven't entered a Project Number on our dashboard the value will still be used from your app until you update.

I recommend contacting OneSignal support with the full details on the app ids you are seeing an issue with and they can look into your account.

Since this is an Android question on an iOS repo I am going to close this issue.

Thanks.

**Comment by mitchellkrogza** [comment]
My apologies, I was in a circle of confusion between web push and other SDK's, George clarified this all for me via email. Thought I had lost users but that was not the case.
