### ISSUE TITLE
Notification callback not called when in foreground

### ISSUE THREAD

**Issue by guidolodetti** [OneSignal/OneSignal-iOS-SDK#190]
Hello,

I cannot display my custom alert when my app is in foreground. It has always worked, but now, with the latest SDK version, I just get in my OneSignal dashboard a "notification clicked" but nothing appears in my app.

This is my current code:
```Swift
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
  OneSignal.initWithLaunchOptions(launchOptions, appId: Globals.oneSignalAppId, handleNotificationAction: { (result) in
      guard let result = result else {
          return
      }
      // Previously I used to use 'result.notification.wasAppInFocus == true'
      if result.notification.wasShown == false && result.notification.isSilentNotification == false {
          // App is in foreground
          // Showing my custom alert
          var title = "UGO"
          if let newTitle = payload.additionalData["title"] as? String {
              title = newTitle
          }
          let message = payload.title
          if let action = payload.additionalData["url"] as? String {
              GLAlertView(title: title, message: message, cancelButtonTitle: "OK", otherButtonTitles: ["Show"]).show({ (alertView, buttonIndex, message) -> Void in
                  if buttonIndex == 1 {
                      if let url = URL(string: action) {
                          self.checkURL(url, sourceApplication: nil)
                      }
                  }
              })
          } else {
              GLAlertView(title: title, message: message, cancelButtonTitle: nil, otherButtonTitles: ["OK"]).show(nil)
          }
      } else {
          // App is not in foreground
          if let urlString = payload.additionalData["url"] as? String {
              if let url = URL(string: urlString) {
                  self.checkURL(url, sourceApplication: nil)
              }
          }
      }
  }, settings: [kOSSettingsKeyInFocusDisplayOption: OSNotificationDisplayType.none.rawValue, kOSSettingsKeyAutoPrompt: false])
}
```

**Comment by jkasten2** [comment]
@guidolodetti Sorry about the confusion on this. Some releases ago we fixed a bug where [`handleNotificationAction`](handleNotificationAction) would fire instead of [`handleNotificationReceived`](https://documentation.onesignal.com/docs/ios-native-sdk#section--handlenotificationreceived-) when `OSNotificationDisplayType.none` was set.

You will need to move your alert display code to the new received call back.

**Comment by guidolodetti** [comment]
Thanks @jkasten2. How do I know if `handleNotificationReceived` is called in the foreground or it is called in background but with `content_available`? I mean, if the app is in the background, and I send a notification with `content_available`, I don't want to trigger my custom alert since the app is not in foreground (even if that callback is fired). This sounds a bit strange.

**Comment by jkasten2** [comment]
@guidolodetti  [`handleNotificationReceived`](https://documentation.onesignal.com/docs/ios-native-sdk#section--handlenotificationreceived-) also has the same [`OSNotification`](https://documentation.onesignal.com/docs/ios-native-sdk#section--osnotification-) object so you can continue to check for `wasShown` and `isSilentNotification ` as you have above.

**Comment by guidolodetti** [comment]
@jkasten2 I don't find it very intuitive, but that works. I have made a common function with my code that gets called from both the callbacks. Thanks.

**Comment by jkasten2** [comment]
@guidolodetti Good to hear that worked for you. What parts specifically wasn't intuitive?

**Comment by guidolodetti** [comment]
@jkasten2 I can't understand why `wasShown` should be `false` when you disable automatic in-app notification. I think there should be only one callback (like before) and a property to know if the app is in foreground or not in order to ease the handle of the notification 🤔

**Comment by jkasten2** [comment]
@guidolodetti Thanks for the feedback. `wasShown` becomes `false` on this callback since that notification was never shown to the user. It won't be displayed in the notification center or as an alert if `kOSSettingsKeyInFocusDisplayOption` is set to `none`.

iOS 10 native events also have 2 different callbacks. One for the opening of the notification [`userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:`](https://developer.apple.com/reference/usernotifications/unusernotificationcenterdelegate/1649501-usernotificationcenter?language=objc) and the other is [`userNotificationCenter:willPresentNotification:withCompletionHandler:`](https://developer.apple.com/reference/usernotifications/unusernotificationcenterdelegate/1649518-usernotificationcenter?language=objc) when it is recieved but before it displayed. The 2nd is a bit different than our received as it allows control over omitting the display of it on a per notification bases. We are considering on change to this pattern in the future.

Let us know if you have any additional feedback on this.
