### ISSUE TITLE
"Close" button in English

### ISSUE THREAD

**Issue by congkinh** [OneSignal/OneSignal-iOS-SDK#197]
Hello,

We are using OneSignal in our application. The application actually supports multiple languages (not only English). But, when the application is open, the notification message arrives and shows a dialog box with "Close" button even though the user is using another language instead of English, for example if the user is using French, the dialog box should show "Fermer" button instead.

Could you tell me is there any way to fix that? Thanks in advance !

**Comment by jkasten2** [comment]
@congkinh We don't have an option to configure the default in focus alert box at this time. I recommend setting [`kOSSettingsKeyInFocusDisplayOption`](https://documentation.onesignal.com/docs/ios-native-sdk#section--kossettingskeyinfocusdisplayoption-) to `Notificaion` which will always display a normal notification when your app is in focus. Alternatively you can set it to `None` instead and then display your own alert from our [`handleNotificationReceived'](https://documentation.onesignal.com/docs/ios-native-sdk#section--handlenotificationreceived-).

**Comment by ovolab** [comment]
We have the same problem.

This is not just a matter of not providing non-English localizations out of the box. I understand you don't have the resources to support dozens of non-English languages. This is a matter of wrapping all UI-facing strings in NSLocalizableString() macros so that individual developers can add their own translations.

If I set an lldb breakpoint in -[NSBundle localizedStringForKey:value:table:] before displaying the in-app notification alert, the breakpoint is never hit. This suggests that you have a hard-coded "Close" string in the code. You probably have an Xcode warning on that line ("User-facing text should use localized string macro"), too, which you chose to ignore.

This is not an unsupported feature. This is a bug that you ought to fix if you want to market your product outside of the USA. Please take localization seriously. Not the whole world speaks English.
