### ISSUE TITLE
Leak on init in iOS

### ISSUE THREAD

**Issue by talkaboutdesign** [OneSignal/OneSignal-iOS-SDK#20]
<img width="1108" alt="screen shot 2016-03-21 at 10 05 49 pm" src="https://cloud.githubusercontent.com/assets/2926534/13940143/2dbb8d7e-efb1-11e5-93e8-71197411dee2.png">

**Comment by jkasten2** [comment]
Thanks for the information, this leak is 80 bytes and will only occur once during app startup so this won't have an impact on your app.

We'll see if there is a way to clean this up so it doesn't pollute the log however going to make this a low priority issue.

**Comment by jeslyvarghese** [comment]
+1

**Comment by skuske** [comment]
Any update on this? Any way to clean that up? Thanks.

**Comment by skuske** [comment]
Actually I am wondering why OneSignal calls

`SKPaymentQueue canMakePayments `

Can someone shed some light on this, please?

![bildschirmfoto 2018-03-01 um 11 40 29](https://user-images.githubusercontent.com/12996815/36840550-a7150876-1d45-11e8-96b4-bcd11d9a64c8.png)

**Comment by jamesstout** [comment]
@skuske It's because OneSignal tracks IAPs: #276

In `initWithLaunchOptions`:
https://github.com/OneSignal/OneSignal-iOS-SDK/blob/5fe84b34470a8b39e2ca7c90e342644e646295c3/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L505

Which calls `SKPaymentQueue canMakePayments`:
https://github.com/OneSignal/OneSignal-iOS-SDK/blob/b3044eb2779cf81b3e1de95b4b3fffae603450ed/iOS_SDK/OneSignalSDK/Source/OneSignalTrackIAP.m#L48-L50

 `SKPaymentQueue canMakePayments` is the source of the leak, so maybe a Radar to Apple?

I did add a settings key `kOSSettingsKeyIAPTracking` to toggle OneSignal IAP tracking a while ago in a branch on my fork. I tidied it up a little and pushed it: https://github.com/OneSignal/OneSignal-iOS-SDK/compare/master...jamesstout:opt-out-iap-tracking

As you saw, with IAP tracking on, just an 80 byte leak:

![screen shot 2018-08-09 at 5 00 18 pm](https://user-images.githubusercontent.com/1576190/43893157-9315b700-9c00-11e8-84e8-302fdbacd6a1.png)

With the IAP tracking off:

![screen shot 2018-08-09 at 4 56 42 pm](https://user-images.githubusercontent.com/1576190/43893216-b4f78cc2-9c00-11e8-9920-d1f5d84e8c53.png)

However, I'm not suggesting a PR; all tests pass, but I don't know what other impact the change could have.

**Comment by skuske** [comment]
@jamesstout

Cool. Thanks a lot! :o)

**Comment by rgomezp** [comment]
Closing since no other reports of this being an issue
