### ISSUE TITLE
kOSSettingsKeyAutoPrompt doesn't work as expected

### ISSUE THREAD

**Issue by arturphoenix** [OneSignal/OneSignal-iOS-SDK#220]
If app has Background Modes - Remote Notifications enabled in `Info.plist`, user is prompted for notifications ignoring `kOSSettingsKeyAutoPrompt` = NO.
It looks like there is error in `+registerForAPNsToken` method ([this line](https://github.com/OneSignal/OneSignal-iOS-SDK/blob/master/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L505)), here should be 'or' condition instead of 'and' because we should stop if any of specified conditions is true.

**Comment by jkasten2** [comment]
@arturphoenix The current code is correct. The device can get a APNs push token as long both the permission is NOT `false`  AND Background modes is NOT enabled.

None of the code in `registerForAPNsToken` will prompt, it only registers the device for a push token.

Could you share your OneSignal init code? Are you seeing the permission prompt or just a seeing `application:didRegisterForRemoteNotificationsWithDeviceToken:` fire on your app delegate?

**Comment by arturphoenix** [comment]
My goal is to show user prompt about notifications on second launch instead of first.
So:
1. I make clean install (first launch after app was deleted)
2. OneSignal initialization looks like this:
`[OneSignal initWithLaunchOptions:launchOptions
                               appId:VOXEnvironmentOneSignalAppId
          handleNotificationReceived:^(OSNotification *notification) {
              processNotificationPayload(notification);
          } handleNotificationAction:^(OSNotificationOpenedResult *result) {
              processNotificationPayload(result.notification);
          }  settings:@{
                                       kOSSettingsKeyAutoPrompt: @NO,
                                       kOSSettingsKeyInAppAlerts: @NO
                                       }];`

As a result `+registerForAPNsToken` called in `+init...` method, and after check specified in my previous comment `[[UIApplication sharedApplication] registerForRemoteNotifications];` called.

And answering you last question, yes, I see permission prompt and after answer `application:didRegisterForRemoteNotificationsWithDeviceToken:` called.
This behavior was reproduced on iOS 10.1 and 10.3.

**Comment by jkasten2** [comment]
@arturphoenix I wasn't able to reproduce the prompt issue with our 2.5.2 SDK on iOS 10.3 with your settings dictionary you listed above.

Can you check to make sure you don't have any extra calls to the following methods?
* `promptForPushNotificationsWithUserResponse`
* `registerForPushNotifications`
* `requestAuthorizationWithOptions`
* `registerUserNotificationSettings`


Are you prompting from `application:didRegisterForRemoteNotificationsWithDeviceToken`? If so I recommend removing this and just using `promptForPushNotificationsWithUserResponse` instead.

Alternatively instead of making code changes to your `application:didRegisterForRemoteNotificationsWithDeviceToken` you could disable Background Modes - Remote Notifications.

**Comment by arturphoenix** [comment]
It's my fault, I've inspected my code again and found call to `-registerUserNotificationSettings:` for local notifications (
Sorry for disturbing and thanks for support.
