### ISSUE TITLE
Filter operator priorities unclear

### ISSUE THREAD

**Issue by novellizator** [OneSignal/OneSignal-iOS-SDK#245]
There's no notion in the documentation what are the priorities. Say I need something like this:

(A or B) and (MONTH1 or MONTH2 or MONTH3) and (C or D)

and have no idea if it is possible to rewrite this condition using your filters ;(  Is it? I know you don't support nesting so i'm trying to expand it 

For clarification: every condition (written in capital letters) is short for something like `{"field": "tag", "key": "somename", "relation": "=", "value": "somevalue"},`

**Comment by jkasten2** [comment]
@novellizator `AND`s have priority over `OR`s. Placing the conditions you have above in order will not give the result your have noted with parenthesis. Since the REST API doesn't support parenthesis or nesting you will have to repeat each `OR` combination with a set of `AND`s to get the same results. With your example this would be.

```
A and MONTH1 AND C
OR
A and MONTH1 AND D
OR
A and MONTH2 AND C
OR
A and MONTH2 AND D
OR
A and MONTH3 AND C
OR
A and MONTH3 AND D
... repeat all of the above with B
```

**Comment by novellizator** [comment]
thank you so much! :) prolly, i'd consider adding it to the documentation as well

**Comment by jkasten2** [comment]
@novellizator Thanks added the `ANDs have priority over ORs.` note to the docs.
