### ISSUE TITLE
Xcode 8.3, Swift 3: No such module 'OneSignal'

### ISSUE THREAD

**Issue by Chhuon** [OneSignal/OneSignal-iOS-SDK#260]
Xcode 8.2.1, Swift 3: No such module 'OneSignal'. I used Notification Service Extension, and I can't import OneSignal into NotificationService.swift. So far I have't got any the solution about it yet.

**Comment by jkasten2** [comment]
@Chhuon If you ran `pod install` before adding the Notification Service Extension you will need to run it again for the library to be linked to the target. Ensure you have both target entries noted in step 2.4 as well.
https://documentation.onesignal.com/docs/ios-sdk-setup#section-2-import-onesignal-into-your-xcode-project

**Comment by yakubpashask** [comment]
Hello, Even we are facing the same issue. we have copied the source in to our project and tried but no luck. Is there any alternate way with pod install. and i found libOnesignal.a in the demo app but it does not locate anywhere.
Please help us.

Thanks
Yakub.

**Comment by jkasten2** [comment]
@yakubpashask We only have setup instructions for [CocoaPods](https://documentation.onesignal.com/docs/ios-sdk-setup) and [Carthage](https://documentation.onesignal.com/docs/carthage-setup) as it takes a number of manual steps and harder to update otherwise. Due to the classes used the SDK you can't directly use the OneSignal source code in your project with the Notification Extension Service. It must be a compiled` .framework`.

The example Xcode project does not include `libOneSignal.a` in it as it will be pulled in when `pod install` is run. Make sure you follow all the required steps on following page to try out the example.
https://github.com/OneSignal/OneSignal-iOS-SDK/tree/master/Examples

When setting up the the SDK with your own project the most common mistakes for the error you are missing the following from your `Podfile`
```ruby
target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 2.5.2', '< 3.0'
end
```

Or not opening the newly created `.xcworkspace` workspace. The `.xcworkspace` should always be opened now instead of the `.xcproj` file.

**Comment by yakubpashask** [comment]
Thank you so much for the detail explanation.. will try to install it through pod and get back to you at the earliest.

**Comment by jkasten2** [comment]
@Chhuon @yakubpashask Feel free to reopen with additional details if you are still seeing this problem.
