### ISSUE TITLE
Featured image (OneSignal WP Plugin) as rich media attachment?

### ISSUE THREAD

**Issue by lddd** [OneSignal/OneSignal-iOS-SDK#269]
Hey there,

is there support for it? Because i tested several times now. Push Notifications sent on new blog posts do not contain the featured image on the device. 

Images with a Image URL sent through OneSignal.com works fine, thumbnails preview appears on the device.

thanks in advance for help.

**Comment by jkasten2** [comment]
@lddd This is due to the [OneSignal-WordPress-Plugin](https://github.com/OneSignal/OneSignal-WordPress-Plugin) not supporting this. It doesn't set the `ios_attachments` field in the REST API call it makes to send the notification.

Could you open another issue on the repo below since this is where the changes would need to be made.
https://github.com/OneSignal/OneSignal-WordPress-Plugin/issues

Thanks.
