### ISSUE TITLE
Unable to add as a dependency

### ISSUE THREAD

**Issue by armandsLa** [OneSignal/OneSignal-iOS-SDK#271]
I was unable to add OneSignal as dependency to a development pod. Seems like this requires some addition configurations described [here](https://github.com/CocoaPods/CocoaPods/issues/5368).

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration

**Comment by jkasten2** [comment]
@armandsLa Is this is still an issue? Since this was opened a while back there have been a number of changes to both this SDK and Cocoapods.

Our React Native SDK depends on this SDK via Cocoapods noted in this podspec.
https://github.com/geektimecoil/react-native-onesignal/blob/3.4.1/react-native-onesignal.podspec#L24-L25

If you are still able to reproduce a problem can you attach an example project?
