### ISSUE TITLE
Swift 4 support 

### ISSUE THREAD

**Issue by zoufishanmehdi** [OneSignal/OneSignal-iOS-SDK#287]
Hi, are there any plans to update to Swift 4 in the near future? Thank you.

**Comment by jkasten2** [comment]
@zoufishanmehdi We haven't switch to Swift from Objective-C as the Swift libraries can add 10mb to 20mb to the app size.
https://stackoverflow.com/questions/28275711/adding-swift-to-project-increase-size-substantiously-how-and-when-can-it-be-avo
https://stackoverflow.com/a/41907555/1244574

There are still a number of apps that have not converted to Swift as well as other frameworks such as Cordova, Unity, Xamarin, etc that don't include Swift by default. We don't want to add the Swift libraries as dependencies due to it's extra size and extra RAM usage. It is something we will keep on eye for the future to see if these requirements change.

Also I have tested the OneSignal 2.5.6 SDK with a Swift 4 project and haven't seen any issues.

**Comment by jstheoriginal** [comment]
I'm using it in my Swift 4 app without issues. I'm using Carthage. I just needed to make sure I ran Carthage update and then it worked.

**Comment by jkasten2** [comment]
Closing the issue as there is no action at this time. We will reevaluate using Swift when future versions are released and the SDK is currently usable by Swift projects.
