### ISSUE TITLE
One signal Notification mismatched bundle id

### ISSUE THREAD

**Issue by ankitbisht143** [OneSignal/OneSignal-iOS-SDK#291]
I am getting one error of mismatched bundle id in sending notifications from one signal website.
I am getting this issue first time. I have sent notifications many time to all my subscribed users but never got this issue. Suddenly I got this today.
My bundle id of my Xcode and the uploaded one is the same.

**Comment by jkasten2** [comment]
The mismatch error can only happen if you send a notification to a user that doesn't match the bundle id on the .p12 file you uploaded. Since you have been using OneSignal for a while and just ran into this it could be from another Xcode project you were testing with.

Did you create a new Xcode project and happen to use the same OneSignal app_id? Or do you have a different bundle id based on dev, staging, and production build of your app?

**Comment by jkasten2** [comment]
@ankitbisht143 Feel free to reopen this issue if the above did not help.

**Comment by electrotechgeek** [comment]
Hi,

I am getting same issue. Xcode bundle id is the same as the certificate but still getting the issue. I am getting same issue on my 3 different projects.
