### ISSUE TITLE
The app version is determined incorrectly

### ISSUE THREAD

**Issue by torben-erz** [OneSignal/OneSignal-iOS-SDK#303]
Wrong in line 1013 of OneSignal.m:
NSString* build = [[NSBundle mainBundle]infoDictionary][(NSString*)kCFBundleVersionKey];

Correct is:
NSString* appVersion = [[[NSBundle mainBundle] infoDictionary] objectForKey:@"CFBundleShortVersionString"];

![image-2017-11-06-17-40-54-036](https://user-images.githubusercontent.com/3204695/32646902-1e558cb6-c5ef-11e7-81d1-90e11d2de711.png)

**Comment by jkasten2** [comment]
@BlueFireCoder We will fix this in the next major release (3.0.0). Since this will be a breaking change for those who are relying on `kCFBundleVersionKey` we won't be able to make this change to a minor or patch version (2.x).

In the mean time I recommend using sendTag to track the app version if you need to use the `CFBundleShortVersionString` type instead.

Thanks.

**Comment by MattiaConfalonieri** [comment]
Approximately when version 3.0.0 go out?

**Comment by emawby** [comment]
Closing issue with Major release beta being available
