### ISSUE TITLE
OneSignal load time

### ISSUE THREAD

**Issue by kamendo** [OneSignal/OneSignal-iOS-SDK#307]
<img width="884" alt="screen shot 2017-11-29 at 18 54 25" src="https://user-images.githubusercontent.com/6680528/33387973-4ff20f36-d537-11e7-9af3-7478f3f11d03.png">

Can I do something about this (delay initialization may be?) Its slowing my app startup time :)

**Comment by bank18651** [comment]
I also got this too.

**Comment by Nightsd01** [comment]
Most of this load time is due to our SDK’s interaction with the Objective-C runtime which can be a bit slow. We do a lot of swizzling so that developers don’t have to add a lot of boilerplate code to their apps. 

I will look into how we can make this more efficient and perhaps delay it so that it doesn’t block initialization of the app itself.

**Comment by chrismanderson** [comment]
One potential solution is to let devs use the SDK without swizzling. I've asked this on the intercom in the past and seen other discussions around it but always seem to get back "swizzling is fine" :grin:. I use Segment for my OneSignal integration precisely because this SDK swizzles.

If swizzling does cause startup time issues, seems like a prime opportunity to build in the functionality to allow it to work without it.

**Comment by revolter** [comment]
Being able to manually initialize the SDK so it doesn't rely on swizzling would be great!

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration

**Comment by alexandre-g** [comment]
Hi, any updates on this? Getting `OneSignal : 500.26 milliseconds ` init time on last gen iPad Air.
Apple's recommended is 400ms for the whole app.
