### ISSUE TITLE
How to properly configure code signing for OneSignalNotificationServiceExtension target?

### ISSUE THREAD

**Issue by AndrewAgapov** [OneSignal/OneSignal-iOS-SDK#309]
Which provisioning profiles i should use for this target? Xcode always give errors when i'm trying to archive my project.

**Comment by Nightsd01** [comment]
@AndrewAgapov I would suggest enabling the automatic provisioning for the OneSignal extension.

**Comment by iulia-geronimo** [comment]
Hello, 

I have the same issue here. I wanted to sign the app automatically, but when uploading to store I get "general error". I tries to create an app ID with com.test.app.OneSignalNotificationServiceExtension, but apple won't allow it. If I remove the dot and leave it as com.test.appOneSignalNotificationServiceExtension, it works, but still not working when uploading it to store. I get the error that the bundle should be  appBuble.extension i.e com.test.app.OneSignalNotificationServiceExtension. So I am kind of stuck.

**Comment by nickthedude** [comment]
Do you mean prefixed?

**Comment by valerybodak** [comment]
@Nightsd01 
Hi, I have the following issue with signing
https://stackoverflow.com/questions/52646820/react-native-onesignal-no-profiles-for-com-myapp-ios-onesignalnotificationser

Could you please help me. Thanks in advance.

**Comment by AntoineBouquet** [comment]
@Nightsd01 I would like to activate app group capability to display badge notification on iOS Ionic app.

Certainly I misunderstand the documentation, I'm also stuck when creating a provisionning profile for OneSignalNotificationServiceExtension project. This means to create a new App Id, with app group and notification capabilities ? So the use of notification capability involved creating new development and production ssl cert ? 

Thanks in advance

**Comment by bohan0** [comment]
Below instructions assume that your app is building and you have successfully deployed TestFlight builds (since that is where I started from)

1. Go to https://developer.apple.com/account/ios/profile
2. Click "+'
3. Choose the type you want of provisioning profile you want (I went with App Store since I use TestFlight builds to test)
4. for App ID choose "XC YOUR_DOMAIN_APP_ID OneSignalNotificationServiceExtension" and make sure enable the App Groups capability
5. after you have downloaded the provisioning profile, go into Xcode, turn off automatically signing on the OneSignalNotificationServiceExtension target in General tab and import the provisioning profile you just downloaded.
6. Use Product > Archive as usual to create your ipa file for App Store upload as usual

**Comment by Cyberben3d** [comment]
Hi bohan0, thanks this is helpful. Can you tell me if we also need to enable App Groups on the main provisioning profile? YOUR_DOMAIN_APP_ID? I am getting an error with App Groups only added to the extension's provisioning profile. Also I'm confused if we need push notifications enabled on both the extension and the main profile. Thanks in advance.

**Comment by bohan0** [comment]
I have App Groups enabled on the main provision profile as well. 

In XCode I did not have Push Notifications enabled under Capabilities for OneSignalNotificationServiceExtension

**Comment by Cyberben3d** [comment]
Hi bohan0, thanks that matches the answer I got from OneSignal support. App Groups on both the main target and the NSE (Notification Service Extension) target profiles. Push Notifications for the main target profile only.

**Comment by jeanlambert17** [comment]
How does this work with AppCenter?
