### ISSUE TITLE
Remove manual didRegisterForRemoteNotificationsWithDeviceToken

### ISSUE THREAD

**Issue by ogres** [OneSignal/OneSignal-iOS-SDK#382]
**Description:**

Hello,
Currently `didRegisterForRemoteNotificationsWithDeviceToken` is called on startup ( even if it is a fresh install and kOSSettingsKeyAutoPrompt is set to false ).

I don't see any reason why it is implemented like this.

The only time OneSignal SDK should call this is after iOS itself calls the Swizzled method and OneSignal will do its job and forward the call to Application.

I'm using token in `didRegisterForRemoteNotificationsWithDeviceToken` and calling it manually even before the token/remote notification permission is requested is very confusing.

I would suggest to remove the code that calls this manually and just forward the function call when iOS tells AppDelegate that user did register with token.

**Environment**
OneSignal 2.8.5
iOS 11.4

**Comment by Nightsd01** [comment]
It is advantageous to call `UIApplication.shared.registerForRemoteNotifications()` as soon as possible because it speeds up the amount of time it takes for the SDK to receive an APNS device token.

Calling this method gets a push token from APNS. It does not prompt/disturb the user in any way. 

Most developers will _not_ call `registerForRemoteNotifications()` themselves, so our SDK does need to do it. If you have a highly specialized/specific case, I would recommend commenting this code out of our SDK. 

I am not sure I understand how this is causing a problem for you?

**Comment by ogres** [comment]
Thanks for the explanation.
