### ISSUE TITLE
Can't use Cocoapods install OneSignal-ios-sdk

### ISSUE THREAD

**Issue by xiaofei730** [OneSignal/OneSignal-iOS-SDK#390]
**Description:**
error:
Cloning into '/var/folders/7b/csmdn1ys6qd3ymw3gzb48x3m0000gn/T/d20180725-27234-1gnlzw6'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Environment**
cocoapods version --1.5.0

**Steps to Reproduce Issue:**

Install iOS SDK version 2.8.5 with Cocoapods into a project

**Anything else:**

**Comment by Nightsd01** [comment]
@xiaofei730 are you saying this error happens when you do `pod install`?

If so, that is definitely not an issue with our SDK. That would be an issue with your local cocoa pods setup.

**Comment by xiaofei730** [comment]
my cocoapods version is 1.5.0 ,and others third library  can pod install ，except OneSignal

**Comment by Nightsd01** [comment]
@xiaofei730 I'm sorry to hear that - but it's _definitely_ an issue with your local cocoapods setup.

I would try the standard Cocoapods troubleshooting steps, like this:

```
sudo rm -fr ~/Library/Caches/CocoaPods/
sudo rm -fr ~/.cocoapods/repos/master/
```

You can also try to remove the folder shown in that error:

```
sudo rm -rf /var/folders/7b/csmdn1ys6qd3ymw3gzb48x3m0000gn/T/d20180725-27234-1gnlzw6
```

If that doesn't work, try reading this:

https://guides.cocoapods.org/using/troubleshooting.html

In any case, closing this issue because it's more of an issue with cocoapods than our SDK.
