### ISSUE TITLE
Can not debug in didReceive() in NotificationService

### ISSUE THREAD

**Issue by luongnhatlam** [OneSignal/OneSignal-iOS-SDK#428]
**Description:**

I set breakpoint and then my app does not stop at break point after received notification. I configure like document. And how can I custom subtitle or title when notification coming??
 override func didReceive(_ request: UNNotificationRequest, withContentHandler contentHandler: @escaping (UNNotificationContent) -> Void) {
        self.receivedRequest = request;
        self.contentHandler = contentHandler
        bestAttemptContent = (request.content.mutableCopy() as? UNMutableNotificationContent)
        
        if let bestAttemptContent = bestAttemptContent {
            OneSignal.didReceiveNotificationExtensionRequest(self.receivedRequest, with: self.bestAttemptContent)
            contentHandler(bestAttemptContent)
        }
    }

**Comment by Nightsd01** [comment]
`UNMutableNotificationContent` has both `title` and `subtitle` properties that you can override before passing it to the completion handler. See [more here](https://developer.apple.com/documentation/usernotifications/unmutablenotificationcontent)

Debugging extensions can be tricky, Xcode does not reliably attach the debugger to the notification service extension. Just keep in mind that the extension is basically like a separate app/separate process. Breakpoints in the extension won’t work if you have the debugger attached to your app and not extension. 

I would suggest googling tips for debugging the notification service extension

Closing because this would not be an issue with our SDK.
