### ISSUE TITLE
About registerUserNotificationSettings

### ISSUE THREAD

**Issue by onmyway133** [OneSignal/OneSignal-iOS-SDK#43]
Hi, in the `init` of `OneSignal` object, you have the logic to call `registerForPushNotifications` https://github.com/OneSignal/OneSignal-iOS-SDK/blob/master/iOS_SDK/OneSignal/OneSignal.m#L293

```swift
// Register this device with Apple's APNS server.
        if (autoRegister || registeredWithApple)
            [self registerForPushNotifications];
        // iOS 8 - Register for remote notifications to get a token now since registerUserNotificationSettings is what shows the prompt.
        else if ([[UIApplication sharedApplication] respondsToSelector:@selector(registerForRemoteNotifications)])
            [[UIApplication sharedApplication] registerForRemoteNotifications];
```

The problem is in `registerForPushNotifications`

```swift
// For iOS 8 devices
    if ([[UIApplication sharedApplication] respondsToSelector:@selector(registerUserNotificationSettings:)]) {
        // ClassFromString to work around pre Xcode 6 link errors when building an app using the OneSignal framework.
        Class uiUserNotificationSettings = NSClassFromString(@"UIUserNotificationSettings");
        NSUInteger notificationTypes = NOTIFICATION_TYPE_ALL;
        
        [[UIApplication sharedApplication] registerUserNotificationSettings:[uiUserNotificationSettings settingsForTypes:notificationTypes categories:nil]];
        [[UIApplication sharedApplication] registerForRemoteNotifications];
    }
```

Here by calling `registerUserNotificationSettings`, you override users' notification settings, which is not a good thing.

> Calling this method with a new user settings object replaces the previous settings request

Here you just pass `nil`, but some users prefer to have their own `categories` specified.

In the case users already call `registerUserNotificationSettings` by themselves, then this call `registerUserNotificationSettings` is redundant, right? Can we have the option to disable this behaviour?

**Comment by JKalash** [comment]
Hi,

UserNotificationCategories are used in order to send remote notifications with actions. Currently, we have our custom implementation of notification buttons made possible by intercepting remote notifications with content-available = 1 with a custom payload for action buttons, and creating a corresponding UILocalNotification with the desired action buttons.

Note that starting our SDK 2.0 which is currently in [beta](https://github.com/OneSignal/OneSignal-iOS-SDK/tree/beta-2.0), the method signature for our Init has changed, allowing the developer to pass customized settings as part of the Init call. We will look into adding a setting option to allow developers to override this behavior using their own notification categories.

Thanks.

**Comment by JKalash** [comment]
As for the code you attached, we will release a fix that will pass the current user notification settings instead of nil, just like we would do before scheduling a local notification.

**Comment by onmyway133** [comment]
@JKalash thanks for your prompt reply. 

I think for a lot of users like us (transitioning from Parse to OneSignal), it means we already call `registerUserNotificationSettings`, so it's best that you don't call `registerUserNotificationSettings` again during `init`.
