### ISSUE TITLE
'initWithTitle:message:delegate:cancelButtonTitle:otherButtonTitles:' available on iOS - Use UIAlertController instead.

### ISSUE THREAD

**Issue by cassianomon** [OneSignal/OneSignal-iOS-SDK#451]
**Description:**

Finished the configuration for the iOS and got the error below:

<img width="1168" alt="screenshot at nov 30 20-45-43" src="https://user-images.githubusercontent.com/12648633/49318862-5ecb4980-f4e1-11e8-9157-62634101063a.png">

**Environment**

Podfile:
```
pod 'react-native-onesignal',
    :path => "../node_modules/react-native-onesignal/react-native-onesignal.podspec",
    :inhibit_warnings => true

target 'Cestou' do
  target 'CestouTests' do
    inherit! :search_paths
  end
end

target 'OneSignalNotificationServiceExtension' do
    pod 'OneSignal', '>= 2.9.3', '< 3.0'
end
```

**Comment by Nightsd01** [comment]
@cassianomon Closing because this is a known issue (#396)

To resolve the issue, please go to the Xcode project settings for your OneSignalNotificationServiceExtension target and set "Require Only App-Extension Safe API" to `No`

In our 3.0 release we will be fixing this issue, but in the mean time, that should be a good workaround.

<img width="653" alt="screen shot 2018-11-30 at 3 36 55 pm" src="https://user-images.githubusercontent.com/8186991/49320352-05015a00-f4b6-11e8-8936-f699d1c837fb.png">

**Comment by cassianomon** [comment]
@Nightsd01 It's already set to NO, I already went through known issues

**Comment by cassianomon** [comment]
I reseted all my changes and just did: 
`npm install react-native-onesignal --save `
`react-native link react-native-onesignal `

and used the javascript starter of OneSignal and it all went well.
