### ISSUE TITLE
Titanium official support

### ISSUE THREAD

**Issue by chmiiller** [OneSignal/OneSignal-iOS-SDK#540]
**Description:**

Hi everyone, I know that this is probably not the best place to ask for help but the Titanium community has a community supported module for the One Signal SDK and because, it is community supported, this SDK is quite behind from the original iOS SDK and we were wondering if that could be "officially" supported instead. Does it have any value for One Signal iOS dev team to look into it?
Here is the module repository:
https://github.com/williamrijksen/com.williamrijksen.onesignal

Thanks!

**Comment by joshualambert** [comment]
@chmiiller Another Titanium developer here. We've got OneSignal in front of thousands of users through a few apps I've released. Would be great for official support from OneSignal.

**Comment by jkasten2** [comment]
@chmiiller @joshualambert Thanks for chiming about support for Titanium with OneSignal. We evaluate adding/mainating support for wrapper SDKs based on demand and growth of a framework. We carefully consider this as we can only support so many wrapper SDKs at a time and still be effective at keeping them all maintained.

At this time we do not plan on creating an official Titanium SDK, however we will keep our eye out if demand changes. However, we would be happy to help contribute to a community driven Titanium SDK where we can. Feel free to at one of the maintainers OneSignal SDKs if there is a native iOS or Android issue you're stuck on. We don't have any specific experience with the Titanium framework itself however.

**Comment by joshualambert** [comment]
Hey @jkasten2 --

I've been recommending your platform for years as a Titanium developer, which led to at least one customer (that I know of) converting to a paid account. I'm about to roll this out to yet another client, but the lack of official Titanium support is a major non-starter. As a community, what would we need to do in order to convince y'all this platform is worth it? I'll go rally support in the Axway Titanium Slack group and get a petition if it'd help convince management over there.

Really love OneSignal. Would love it even more with some support love. :)

![giphy](https://user-images.githubusercontent.com/1421842/65921766-c1fb6600-e3a8-11e9-933a-5b833ca698a1.gif)

**Comment by rgomezp** [comment]
We will close this issue. Note that this doesn't mean we won't continue consideration for Titanium support. Thanks for bringing this up

**Comment by chmiiller** [comment]
any news on this @jkasten2 or @rgomezp ? You have support for a lot of different platforms, even Adobe Air, and no news on supporting Titanium? That's a lot of people trying to use it - including me - and not having success on updating the library with newer SDKs
<img width="253" alt="Screen Shot 2020-02-20 at 5 43 52 PM" src="https://user-images.githubusercontent.com/1013632/74958028-a6046980-5408-11ea-9c99-347d7f8e70e4.png">

**Comment by rgomezp** [comment]
Howdy, 
We're still considering this. However, we currently don't have the bandwidth to prioritize this. As soon as we're able we will add support. This doesn't look like the near future. Just managing expectations
