### ISSUE TITLE
Missing userId on iOS 13 (it's always null)

### ISSUE THREAD

**Issue by nicolla1003** [OneSignal/OneSignal-iOS-SDK#558]
**Description:**

We have a problem on iOS with `userId` being null.
Devices with iOS 12 and lower are working ok, but on iOS 13 `userId` is always `null`.
So, `OneSignal.getPermissionSubscriptionState()?.subscriptionStatus.userId` always return null.

**Environment**

We are using the latest iOS SDK version with cocoapods.

**Steps to Reproduce Issue:**

Install any SDK version as it's not so important. We tried a couple of latest versions and behavior was the same every time.

**Comment by nicolla1003** [comment]
I have found what is the problem.
In method  `onOSSubscriptionChanged(_ stateChanges: OSSubscriptionStateChanges!)` we were geting the value for userId with `OneSignal.getPermissionSubscriptionState()?.subscriptionStatus.userId`.

In iOS 13 this doesn't work as userId is always null, but using `stateChanges.to.userId` to get the userId is working.

**Comment by rgomezp** [comment]
You shouldn't be calling `getPermissionSubscriptionState` from within the subscription observer. The behavior you're describing makes sense since this will fire when the state changes from unsubscribed to subscribed the very first time the user opts into notifications. The observer will fire twice. The first time, the userId should be null. It only becomes defined in the second firing. 

You can get it in the second firing with a conditional:
```
func onOSSubscriptionChanged(_ stateChanges: OSSubscriptionStateChanges!) {
      if !stateChanges.from.subscribed && stateChanges.to.subscribed {
         print("Subscribed for OneSignal push notifications!")
         // get player ID
         stateChanges.to.userId
      }
      print("SubscriptionStateChange: \n\(stateChanges)")
   }
```
