### ISSUE TITLE
Check for OSNotificationDisplayType

### ISSUE THREAD

**Issue by helkarli** [OneSignal/OneSignal-iOS-SDK#80]
I want to check if the app was opened from the notification itself or an app alert. How can I do that in Swift? 

In the old SDK there was a parameter isActive in the `initWithLaunchingOptions:launchOptions:appId:handleNotifications`.
As I understand I can check for the `OSNotificationDisplayType` in the notification of the notificationResult in `initWithLaunchOptions:launchOptions:appID:handleNotificationAction` but the Objective C code does not translate properly to Swift or am I missing something here?

`
OneSignal.initWithLaunchOptions(launchOptions, 
appId: "xxxx-appid-xxxx", 
handleNotificationAction: { (notificationResult) in
           let appOpenedFromAlert: Bool = notificationResult.notification.displayType == //?//
}, 
settings: [kOSSettingsKeyInAppAlerts: true, kOSSettingsKeyAutoPrompt: false])
`

**Comment by joaomirandas** [comment]
I can't imagine how use this SDK with swift, have a lot of erros and i do no how fix this, sounds like not be really translated to Swift, this an machine conversion to swift?! Folks help!!

**Comment by JKalash** [comment]
Hi there,

The errors you may be getting is due to the recent changes made to the Swift language. ([Swift 3.0](https://swift.org/blog/swift-3-0-released/)). Our iOS SDK is written in Objective-C but that does not stop anyone from including it in their `Swift Projects`. We include a module-map with our framework that you download from CocoaPods / Carthage that helps Xcode translate our obj-c `OneSignal.h` to the Swift version of it, based on the Swift version you're using with your project.

As for the notification checking, checking the OSNotificationDisplayType may work but a more subtle and straightforward solution would be to check if `UIApplication.shared.applicationState == .active`. if that's the case then the user was in the app when he reacted to the notification, otherwise it was a tap on the notification that forced the app to either launch, or wake up from background state.

**Comment by JKalash** [comment]
@helkarli please feel free to check our included [Swift Example project](https://github.com/OneSignal/OneSignal-iOS-SDK/tree/master/OneSignalSwiftExample) to get you started

**Comment by helkarli** [comment]
Thank you @JKalash for your fast answer. Using `UIApplication.shared.applicationState == .active` does work for me.
