### ISSUE TITLE
One Signal SDK will only ever pull the latest version of CocoaPods and that's a problem when XCode 12 isn't available yet.

### ISSUE THREAD

**Issue by JamesAiken** [OneSignal/OneSignal-iOS-SDK#814]
**Description:**

Hello, I'm a Unity Developer actually, but with using One Signal in Unity you make use of the IOS and Android segments as well if you release your app on both. 

Recently a new beta update for the One Signal Cocoapods came out. This was last night on November 23rd. With this, our Unity Cloud Builds started to fail. The reason is because Unity Cloud Build DOES NOT have XCode 12 available for it yet and it won't be available until Mid-December. This recent update for cocoapods was built using XCode 12, and so that means its not compatible, and therefore we cannot build and release. That's the gist of it.

With this, I have some questions. Why doesn't One Signal specify in their dependencies file for Unity which Pods version it should try to pull? What would be the correct formatting for specifying which version to pull?

I tried doing...

```
  <iosPods>
    <iosPod name="OneSignal" version="~> 2.16.0"/>
  </iosPods>
```

However, this actually leads to 2.16.0, plus the most recent version being pulled and that creates errors for duplicate files.

If able, this is actually a pretty bad issue that should be focused on because you don't know how many other Unity developers will face this problem now.
(your description here)

**Environment**
 Unity Package. But cocoapods is used in Unity Cloud Build to bring out any additional files/content needed for the IOS Build.

**Steps to Reproduce Issue:**

1. Attempt to build a Unity Project using Unity Cloud Build with the One Signal SDK for it. You would use XCode version 11.4.1.
1. 
1. 

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by jkasten2** [comment]
@JamesAiken We ship a local build of this native `OneSignal-iOS-SDK` with the `OneSignal-Unity-SDK`, you will find this under [`Assets/OneSignal/Platforms/iOS/`](https://github.com/OneSignal/OneSignal-Unity-SDK/tree/2.13.1/OneSignalExample/Assets/OneSignal/Platforms/iOS). Cocoapods isn't part of the [OneSIgnal Unity SDK setup guide]( https://documentation.onesignal.com/docs/unity-sdk-setup).

Due to a locally copy of the iOS SDK being provided with the Unity package you may run into duplicated files issues as you noted if you also pull in OneSIgnal via Cocoapods. If you prefer to use Cocoapods instead I recommend deleting `Assets/OneSignal/Platforms/iOS/`. However I would recommend not pulling OneSignal from Cocoapods as it isn't something OneSignal tests and it's included locally copy ensures it matching the C# binding provided with the other part of the SDK.

If you have follow up questions with the OneSignal Unity SD please open a new issue on that repo.
https://github.com/OneSignal/OneSignal-Unity-SDK/issues

Thanks.
