### ISSUE TITLE
Image attachment not displayed in rich notification service extension

### ISSUE THREAD

**Issue by vinayak-nickelfox** [OneSignal/OneSignal-iOS-SDK#978]
**Description:**

I'm using OneSignal to trigger notification in app. I setup everything according the documentation and notifications are working fine. But, the problem is whenever I tried to attached image in the payload it won't displayed in the notification. Later I realised NoitificationServiceExtension in not being called maybe. 

**Environment**
1. iOS SDK - >= 3.0.0', '< 4.0
2. I'm using Cocoapods for adding OneSignal SDK

**Comment by emawby** [comment]
@vinayak-nickelfox Hello thank you for reaching out. To determine if the `NotificationServiceExtension` is being run lets try the following:
1. Verify that the `NotificationServiceExtension` is embedded in your App target under the Frameworks, Libraries, and Embedded Content section of the General tab. 
2. Enable verbose logging in the `NotificationServiceExtension`'s didReceiveNotificationRequest method using `OneSignal.setLogLevel(.LL_VERBOSE, visualLevel: .LL_NONE)` or the Objc equivalent. 
3. To view the `NotificationServiceExtension`'s process go to 'Window' -> 'Devices And Simulators' -> 'Open Console' for the device you are using. Click start streaming to stream the device logs to this window.
4. Send yourself a notification and in the search bar of the device console search for 'NSE request received'. If that is never logged (you need verbose logging to be on) then your `NotificationServiceExtension` is not being run.
5. If 'NSE request received' does appear in the console's logs then right click on that log message and select 'Show Process' in order to see logs for the entire process. You may need to remove the 'NSE request received' filter from the search bar to see all the messages.
6. Then if you could paste the output of that process hear to help with debugging that would be great. Note that it can take some time for the `NotificationServiceExtension` to download the image once the request has been received on the device, but the whole process should never take longer than 25 seconds.

**Comment by vinayak-nickelfox** [comment]
Found the issue. The real culprit was NSExtensionPrincipalClass in service extension info.plist where naming extension were written as my OneSignal Manager class. Now changed to `$(PRODUCT_MODULE_NAME).NotificationService` fixed the issue.
